import { StyleSheet } from "react-native";
import { ITheme } from "@/configs/theme/types";

export const createStyles = (theme: ITheme) =>
  StyleSheet.create({
    card: {
      backgroundColor: theme.colors.card,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: `${theme.colors.primary}18`,
      overflow: "hidden",
      flex: 1,
    },
    imageWrapper: {
      width: "100%",
      aspectRatio: 1.35,
      backgroundColor: `${theme.colors.primary}10`,
      position: "relative",
    },
    image: {
      width: "100%",
      height: "100%",
    },
    ratingBadge: {
      position: "absolute",
      top: 6,
      right: 6,
      backgroundColor: "rgba(0, 0, 0, 0.65)",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      flexDirection: "row",
      alignItems: "center",
      zIndex: 2,
    },
    starText: {
      color: "#FFD700",
      fontSize: 10,
      marginRight: 2,
    },
    ratingText: {
      fontFamily: "BarlowCondensed_600SemiBold",
      fontSize: 11,
      color: "#FFFFFF",
      fontWeight: "bold",
    },
    comingSoonBadge: {
      position: "absolute",
      top: 6,
      left: 6,
      backgroundColor: theme.colors.warning,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      zIndex: 2,
    },
    comingSoonText: {
      fontFamily: "BarlowCondensed_600SemiBold",
      fontSize: 10,
      color: "#FFFFFF",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    premiumBadge: {
      position: "absolute",
      top: 6,
      left: 6,
      backgroundColor: "rgba(0, 0, 0, 0.65)",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      zIndex: 2,
    },
    premiumBadgeText: {
      fontFamily: "BarlowCondensed_600SemiBold",
      fontSize: 10,
      color: "#FFD700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    imageProgressContainer: {
      position: "absolute",
      bottom: 6,
      left: 6,
      right: 6,
      backgroundColor: "rgba(0, 0, 0, 0.60)",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      zIndex: 2,
    },
    imageProgressBackground: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      backgroundColor: "rgba(255, 255, 255, 0.28)",
      overflow: "hidden",
    },
    imageProgressFill: {
      height: "100%",
      backgroundColor: theme.colors.primary,
      borderRadius: 2,
    },
    imageProgressText: {
      fontFamily: "BarlowCondensed_600SemiBold",
      fontSize: 10,
      color: "#FFFFFF",
      minWidth: 26,
      textAlign: "right",
    },
    content: {
      padding: 12,
      flex: 1,
      justifyContent: "flex-start",
    },
    title: {
      ...theme.text("sm", "semibold"),
      color: theme.colors.text,
      lineHeight: 18,
      marginBottom: 4,
      minHeight: 36, // Garante que cards com 1 ou 2 linhas mantenham alinhamento milimétrico
    },
    metadata: {
      ...theme.text("xs", "regular"),
      color: theme.colors.textSecondary,
    },
  });
