import { StyleSheet } from "react-native";
import { ITheme } from "@/configs/theme/types";

export const createStyles = (theme: ITheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
      justifyContent: "center",
      alignItems: "center",
      padding: theme.spacing.md,
    },
    errorText: {
      ...theme.text("md", "regular"),
      color: theme.colors.textSecondary,
      textAlign: "center",
      marginBottom: theme.spacing.md,
    },
    scrollContent: {
      flexGrow: 1,
      backgroundColor: theme.colors.background,
      padding: theme.spacing.md,
      alignItems: "center",
      paddingBottom: 40,
    },
    header: {
      marginBottom: theme.spacing.xl,
      alignItems: "center",
      marginTop: theme.spacing.lg,
    },
    headerTitle: {
      ...theme.text("xxl", "bold"),
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: theme.spacing.xs,
    },
    headerSubtitle: {
      ...theme.text("md", "regular"),
      color: theme.colors.textSecondary,
      textAlign: "center",
    },
    certificateContainer: {
      backgroundColor: "#FFF",
      borderRadius: theme.radius.sm,
      padding: theme.spacing.md,
      width: "100%",
      aspectRatio: 1.41,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 5,
    },
    certificateBorder: {
      flex: 1,
      borderWidth: 2,
      borderColor: theme.colors.primary,
      padding: theme.spacing.xs,
    },
    certificateInnerBorder: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.primary,
      borderStyle: "dashed",
      padding: theme.spacing.md,
      alignItems: "center",
      justifyContent: "space-between",
    },
    certHeader: {
      alignItems: "center",
    },
    certIcon: {
      marginBottom: theme.spacing.xs,
    },
    certTitle: {
      fontFamily: "Oswald_700Bold",
      fontSize: 24,
      color: theme.colors.primary,
      letterSpacing: 2,
    },
    certSubtitle: {
      fontFamily: "BarlowCondensed_400Regular",
      fontSize: 12,
      color: "#666",
      letterSpacing: 4,
      textTransform: "uppercase",
    },
    certBody: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      paddingVertical: theme.spacing.md,
    },
    certText: {
      fontFamily: "BarlowCondensed_400Regular",
      fontSize: 14,
      color: "#333",
      textAlign: "center",
      marginBottom: theme.spacing.xs,
    },
    studentName: {
      fontFamily: "Allura_400Regular",
      fontSize: 28,
      color: theme.colors.primary,
      textAlign: "center",
      marginVertical: theme.spacing.xs,
    },
    courseTitle: {
      fontFamily: "Oswald_700Bold",
      fontSize: 18,
      color: "#333",
      textAlign: "center",
      marginBottom: theme.spacing.lg,
      textTransform: "uppercase",
    },
    metadataContainer: {
      flexDirection: "row",
      justifyContent: "center",
      width: "100%",
      gap: theme.spacing.lg,
      marginBottom: theme.spacing.md,
    },
    metadataItem: {
      alignItems: "center",
    },
    metadataLabel: {
      fontFamily: "BarlowCondensed_400Regular",
      fontSize: 10,
      color: "#888",
      textTransform: "uppercase",
    },
    metadataValue: {
      fontFamily: "BarlowCondensed_600SemiBold",
      fontSize: 14,
      color: "#333",
    },
    dateText: {
      fontFamily: "BarlowCondensed_400Regular",
      fontSize: 12,
      color: "#666",
      marginTop: theme.spacing.md,
    },
    certFooter: {
      width: "100%",
      alignItems: "center",
    },
    signatureLine: {
      width: 100,
      height: 1,
      backgroundColor: "#333",
      marginBottom: 4,
    },
    signatureText: {
      fontFamily: "BarlowCondensed_400Regular_Italic",
      fontSize: 12,
      color: "#333",
    },
    certHash: {
      fontFamily: "BarlowCondensed_400Regular",
      fontSize: 10,
      color: "#CCC",
      marginTop: theme.spacing.xs,
    },
    actionsContainer: {
      width: "100%",
      marginTop: theme.spacing.xl,
      gap: theme.spacing.md,
    },
    shareButton: {
      backgroundColor: theme.colors.primary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: theme.spacing.md,
      borderRadius: theme.radius.md,
      gap: theme.spacing.sm,
    },
    shareButtonText: {
      ...theme.text("lg", "semibold"),
      color: "#FFF",
    },
    homeButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: theme.spacing.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.radius.md,
      gap: theme.spacing.sm,
    },
    homeButtonText: {
      ...theme.text("lg", "medium"),
      color: theme.colors.text,
    },
  });
